# LangChain Agent 共享配置

# 默认 LLM 配置
llm:
  provider: "openai"
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000
  timeout: 30

# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  rotation: "10 MB"
  retention: "7 days"

# 工具配置
tools:
  weather:
    provider: "openweathermap"
    cache_timeout: 300  # 5分钟
    default_units: "metric"
  
  calculator:
    max_expression_length: 100
    allowed_functions: ["sin", "cos", "tan", "log", "sqrt", "abs"]
  
  file_ops:
    max_file_size: 1048576  # 1MB
    allowed_extensions: [".txt", ".md", ".json", ".csv"]
    base_directory: "./data"

# 内存配置
memory:
  type: "buffer"
  max_token_limit: 2000
  return_messages: true

# Web UI 配置
web_ui:
  theme: "default"
  title: "LangChain Agent Assistant"
  description: "基于 LangChain 的智能助手"
  max_chat_history: 50

# 安全配置
security:
  rate_limit:
    max_requests_per_minute: 60
  input_validation:
    max_input_length: 1000
    forbidden_patterns: ["eval", "exec", "import os", "subprocess"]